services:
    - type: web
      name: salary-analysis-dashboard
      env: python
      buildCommand: "pip install -r requirements.txt"
      startCommand: gunicorn --chdir src app:server
      plan: free
